"use client";
//import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import React, { ReactNode } from "react";
import "./globals.scss";
//import Navbar from "commons/navbar/Navbar";
import { Provider } from "react-redux";
import store from "state/store";
import RoutesProtection from "../components/routesProtection/routesProtection";
//import { useSelector } from "react-redux";
//import { RootState } from "../state/store";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "700", "300", "400", "500"],
});

//No está permitido usar Metadata con useClient
/* export const metadata: Metadata = {
  title: "Box Delivery App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }: { children: ReactNode }) {
  // const user = useSelector((state: RootState) => state.user);

  return (
    <html lang="en">
      <Provider store={store}>
        <body className={`${roboto.className} body`}>
          {/* {user.id ? <Navbar /> : null} */}
          <RoutesProtection>{children}</RoutesProtection>
        </body>
      </Provider>
    </html>
  );
}
