export const fakeData = [
  {
    packageNumber: "#0H167",
    address: "Las Heras 5678",
    city: "Buenos Aires",
    status: "pendiente",
  },
  {
    packageNumber: "#A3B92",
    address: "Av. Rivadavia 1234",
    city: "Cordoba",
    status: "en-curso",
  },
  {
    packageNumber: "#7C5F1",
    address: "San Martin 987",
    city: "Rosario",
    status: "entregado",
  },
  {
    packageNumber: "#K9E46",
    address: "Belgrano 4321",
    city: "Mendoza",
    status: "pendiente",
  },
  {
    packageNumber: "#2J8D5",
    address: "9 de Julio 654",
    city: "Mar del Plata",
    status: "en-curso",
  },
  {
    packageNumber: "#R1G73",
    address: "Independencia 789",
    city: "Tucuman",
    status: "entregado",
  },
  {
    packageNumber: "#Y6T29",
    address: "San Juan 876",
    city: "Salta",
    status: "pendiente",
  },
  {
    packageNumber: "#N4S51",
    address: "San Luis 543",
    city: "Jujuy",
    status: "en-curso",
  },
  {
    packageNumber: "#E7W38",
    address: "Santa Fe 210",
    city: "Neuquen",
    status: "entregado",
  },
  {
    packageNumber: "#B2Q94",
    address: "La Rioja 987",
    city: "Formosa",
    status: "pendiente",
  },
  {
    packageNumber: "#F5X82",
    address: "Sarmiento 654",
    city: "San Juan",
    status: "en-curso",
  },
  {
    packageNumber: "#C8Z59",
    address: "San Martin 321",
    city: "La Plata",
    status: "entregado",
  },
  {
    packageNumber: "#P1U76",
    address: "Corrientes 876",
    city: "Santa Cruz",
    status: "pendiente",
  },
  {
    packageNumber: "#L4V63",
    address: "San Juan 543",
    city: "Tierra del Fuego",
    status: "en-curso",
  },
  {
    packageNumber: "#G7T29",
    address: "San Luis 210",
    city: "Chubut",
    status: "entregado",
  },
  {
    packageNumber: "#Z9B47",
    address: "Santa Fe 987",
    city: "Catamarca",
    status: "pendiente",
  },
  {
    packageNumber: "#O2C84",
    address: "La Rioja 654",
    city: "La Rioja",
    status: "en-curso",
  },
  {
    packageNumber: "#H5D62",
    address: "Sarmiento 321",
    city: "Santiago del Estero",
    status: "entregado",
  },
  {
    packageNumber: "#W8F39",
    address: "Corrientes 210",
    city: "San Luis",
    status: "pendiente",
  },
];
